# Generated by Django 2.0.6 on 2018-08-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('realname', models.CharField(max_length=64)),
                ('sex', models.BooleanField(choices=[(0, '女'), (1, '男')], default=0)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
