# Generated by Django 2.0.6 on 2018-08-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180831_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'URL权限表'},
        ),
        migrations.AlterUniqueTogether(
            name='permission2role',
            unique_together={('p', 'r')},
        ),
        migrations.AlterUniqueTogether(
            name='user2role',
            unique_together={('u', 'r')},
        ),
    ]
