# Generated by Django 2.0.6 on 2018-09-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180831_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
