# Generated by Django 2.0.6 on 2018-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_envlists_projects_workorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
