# Generated by Django 2.0.6 on 2018-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20180905_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
